config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'home#index'

  resources :pets do
    get :feed
    get :play
    patch :adopt
  end

  resources :users do
    resources :pets
    resources :friends, controller: 'friendships'
  end

  get "/about" => "home#about"
  get "/faq" => "home#faq"
  get "/contact" => "home#contact"
  get "/leaderboard" => "home#leaderboard"
  get "/shelter" => "pets#new"
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_one :pet_hunger, dependent: :destroy
  has_one :pet_tiredness, dependent: :destroy
  has_one :pet_boredom, dependent: :destroy
  validates :name, presence: true
  validates :type, presence: true, inclusion: { in: %w(Dog Cat Bird Rabbit),
    message: "%{value} is not an available type of pet." }
  validates :gender, presence: true, inclusion: { in: %w(Female Male)}
  before_create :initialize_pet

  scope :dogs, -> {where(type: "Dog")}
  scope :cats, -> {where(type: "Cat")}
  scope :birds, -> {where(type: "Bird")}
  scope :rabbits, -> {where(type: "Rabbit")}

  def update_happiness(current_time)
    self.pet_hunger.increase(current_time)
    self.pet_tiredness.increase(current_time)
    self.pet_boredom.increase(current_time)
    self.calculate_happiness
  end

  def calculate_happiness
    self.happiness = ((100 - self.pet_hunger.value)/2 + (100 - self.pet_boredom.value)/2)
    self.happiness = 100 if self.happiness > 100
    happy_value = self.happiness < 40 ? "sad" : "happy"
    self.img_loc = "#{self.type.downcase}_#{happy_value}.svg"
    self.body_img = "#{self.type.downcase}.svg"
  end

private
  def initialize_pet
    self.happiness = 100
    self.img_loc = "#{self.type.downcase}_happy.svg"
    self.pet_hunger = PetHunger.new(pet_id: self.id)
    self.pet_tiredness = PetTiredness.new(pet_id: self.id)
    self.pet_boredom = PetBoredom.new(pet_id: self.id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, except: [:new, :index, :create]
  before_action :authenticate_user!, except: [:index, :show]

  def feed
    if @pet.pet_hunger.decrease
      if @pet.happiness >= 80
        owner = User.find(@pet.user_id)
        owner.points += 25
        owner.save
      end
      current_user.earn_points
      redirect_to pet_path(@pet), notice: t("pets.feed_success", name: @pet.name)
    else
      redirect_to pet_path(@pet), notice: t("pets.feed_failure", name: @pet.name)
    end
  end

  def play
    if @pet.pet_boredom.decrease
      if @pet.happiness >= 80
        owner = User.find(@pet.user_id)
        owner.points += 25
        owner.save
      end
      current_user.earn_points
      redirect_to pet_path(@pet), notice: t("pets.play_success", name: @pet.name)
    else
      redirect_to pet_path(@pet), notice: t("pets.play_failure", name: @pet.name)
    end
  end

  def show
    @pet.update_happiness(Time.now)
    @owner = User.find(@pet.user_id)
    event
  end

  def new
    @user = current_user
    @pets = User.find(1).pets
    if @pets.count < 18
      until @pets.count == 18
        @pet = generate_pet
        give_to_shelter
      end
    end
    if params[:type]
      @pets = @pets.where(:type => params[:type])
      @pets = @pets.page(params[:page]).per_page(5)
    else
      @featured = @pets.sample
      @pets = @pets.page(params[:page]).per_page(5)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def adopt
    redirect_to user_path(current_user), notice: t("pets.too_many") and return if current_user.pets.count >= current_user.pet_slots
    respond_to do |format|
      if @pet.save
        normalize_pet_stats
        current_user.pets << @pet
        format.html { redirect_to pet_path(@pet), notice: t("pets.new") }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to user_path(current_user) }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pet.previous_owner = current_user.username
    current_user.pets = current_user.pets.to_a.reject! { |p| p.id == @pet.id }
    current_user.points = current_user.points/2
    current_user.save
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: "You abandoned #{@pet.name}." }
      format.json { head :no_content }
    end
    give_to_shelter
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = params[:id].nil? ? Pet.find(params[:pet_id]) : Pet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).permit(:name, :type, :gender, :breed)
  end

  def give_to_shelter
    shelter = User.find(1)
    @pet.name = "My Owner Was a Bad Person" if Obscenity.profane?(@pet.name)
    @pet.name = PetsHelper::NEUTRAL_NAMES.sample if ApplicationHelper.obscene_substring?(@pet.name)
    shelter.pets.first.destroy if shelter.pets.count >= 20
    shelter.pets << @pet
  end

  def generate_pet
    @pet = Pet.new
    @pet.gender = PetsHelper::GENDERS.sample
    @pet.name = @pet.gender == "Female" ? (PetsHelper::FEMALE_NAMES + PetsHelper::NEUTRAL_NAMES).sample : (PetsHelper::MALE_NAMES + PetsHelper::NEUTRAL_NAMES).sample
    @pet.type = PetsHelper::TYPES.sample
    @pet.breed = @pet.type.constantize::BREEDS.sample
    @pet.story = PetsHelper.generate_story(@pet.name, @pet.type, @pet.gender)
    @pet
  end

  def normalize_pet_stats
    @pet.pet_hunger.value = 20
    @pet.pet_tiredness.value = 0
    @pet.pet_boredom.value = 75
    @pet.pet_hunger.save
    @pet.pet_tiredness.save
    @pet.pet_boredom.save
  end

  def event
    unless @pet.user_id == 1 || flash[:notice]
      if @pet.pet_boredom.value > 90
        flash[:alert] = t("pets.bored_#{1+rand(2)}", name: @pet.name, gender: @pet.gender == 'Male' ? 'he' : 'she', owner: current_user == @pet.user ? "your" : @pet.user.username )
      elsif @pet.pet_hunger.value > 90
        flash[:alert] = t("pets.hungry_#{1+rand(3)}", name: @pet.name, gender: @pet.gender == 'Male' ? 'he' : 'she', owner: current_user == @pet.user ? "your" : @pet.user.username )
      elsif @pet.happiness > 90
        flash[:notice] = t("pets.happy_#{1+rand(2)}", name: @pet.name, gender: @pet.gender == 'Male' ? 'he' : 'she', owner: current_user == @pet.user ? "your" : @pet.user.username )
      end
    end
  end

end

app/helpers/pets_helper.rb
module PetsHelper

  MALE_NAMES = ["Thor","Neo", "Hector", "Tony", "Peter", "Bruce", "Clark", "Samuel",
            "Lorenzo", "Reynaldo", "Raymondo", "Guillermo", "Theo", "Spike", "Joey",
            "Buddy", "Woody", "Clint", "Lord Whitby, Esquire", "Bob", "Timmy", "Jake", "Louis", "Chip", "King", "Tommy", "Dakota", "Speckles", "Winston", "Camo"]
  FEMALE_NAMES = ["Ruby", "Sophie", "Pandora", "Pepper", "Natasha", "Elisabeth", "Monica",
                  "Betsy", "Betty", "Phoebe", "Diana", "Queen Elizabeth the Second", "Sally", "Callie", "Karen", "Jenny", "Princess", "Abby", "Chelsea", "Ginger"]
  NEUTRAL_NAMES = ["Spot", "Halo", "Scout", "AJ", "Killer", "Robin", "Lucky"]
  TYPES = ["Dog", "Cat", "Bird", "Rabbit"]
  GENDERS = ["Male", "Female"]

  def self.generate_story(name, type, gender, previous_owner = nil)
    stay = "#{name} has been here at the shelter for #{rand(2..25)} #{["days","weeks","months"].sample}. "
    past1 = "We found #{gender == "Female" ? "her":"him" } abandoned, living on the street. "
    past2 = "#{gender == "Female" ? "She":"He" } was dropped off by an elderly #{["gentleman", "lady"].sample} who said they were unable to care for #{name} anymore. "
    past3 = "#{gender == "Female" ? "Her":"His" } owner had to move, and they couldn't take #{name} with them. "
    past4 = "We were able to rescue #{gender == "Female" ? "her":"him" } from an abusive owner. "
    past5 = ""
    pros1 = "#{gender == "Female" ? "She":"He" } loves #{["other #{type.downcase.pluralize}.","to meet new people.","playing with kids.","the outdoors.","food - maybe a little too much!","getting new toys."].sample} "
    pros2 = "#{gender == "Female" ? "She":"He" } is #{["very","really","extremely","","very"].sample} #{["playful","friendly","talkative","energetic","intelligent"].sample}. "
    cons1 = "#{gender == "Female" ? "She":"He" } has had some #{["leg","eye","eating","movement","hearing","digestion","socialization"].sample} issues in the past, "
    cons2 = "#{gender == "Female" ? "She":"He" } doesn't always #{["get along with","appreciate","like","do well with"].sample} #{["everyone","teenagers","loud noises","the vet","sudden movements"].sample}, "
    leave1 = "but we hope that won't stop the two of you from being great friends!"
    leave2 = "but we're sure #{gender == "Female" ? "she":"he" } will be a great friend for you."
    story = stay + [past1,past2,past3,past4].sample + [pros1,pros2].sample + [cons1,cons2].sample + [leave1,leave2].sample
    return story
  end
end

app/views/pets/_nameform.html.erb
<%= form_for(@pet, as: :pet, url: pet_path(@pet)) do |f| %>

  <% if @pet.errors.any? %>
    <!-- @KL let's semantify this as well, once we can get something to generate it. -->
    <div id="error_explanation" class="alert-box alert radius" align="center">
      <h5><%= pluralize(@pet.errors.count, "error") %> prohibited your pet's info from being saved:</h5>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- @KL where does this label originate from/point to?  I input the "enter a new name" -->
  <%= f.label :name, "What would you like to rename #{@pet.name}?" %>

  <!-- @KL I think we should put a placeholder here, if possible, maybe even mess with the label function Dale showed us -->
  <%= f.text_field :name, placeholder: "New Name", value: "" %>


  <%= f.submit "Rename Pet", class: "btn-profile" %>
<% end %>

app/views/pets/_randomform.html.erb
<% if @featured.errors.any? %>
  <div id="error_explanation" class="alert-box alert radius" align="center">
    <h5><%= pluralize(@featured.errors.count, "error") %> prohibited your pet's info from being saved:</h5>

    <ul>
    <% @featured.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= link_to image_tag(@featured.img_loc), user_pet_path(current_user, @featured) %>
<h2>About this pet:</h2>
<p>Name: <%= @featured.name %></p>
<p>Species: <%= @featured.type %></p>
<p>Breed: <%= @featured.breed %></p>
<p>Gender: <%= @featured.gender %></p>
<p><%= @featured.story %></p>

<%= link_to "Adopt Pet", pet_adopt_path(@featured), method: :patch, class: "btn-profile", data: { confirm: "Adopt #{ @featured.name }?" } %>
<%= link_to "See Another Pet", new_pet_path, class: "btn-profile" %>

app/views/pets/_shelterform.html.erb
<% @pets.each do |pet| %>
	<section class="pet profile shelter index">
		<% pet.update_happiness(Time.now) %>
	  <%= link_to image_tag(pet.img_loc), user_pet_path(current_user, pet) %>
	  <h2>About <%= pet.name %></h2>
	  <p>Species: <%= pet.type %></p>
	  <p>Breed: <%= pet.breed %></p>
	  <p>Gender: <%= pet.gender %></p>
	  <%= link_to "Adopt Pet", pet_adopt_path(pet), method: :patch, class: "btn-profile", data: { confirm: "Adopt #{ pet.name }?" } %>
	</section>
<% end %>

app/views/pets/_status_bars.html.erb
  <% v = @pet.happiness %>
  
  <div class="<%= v > 40 ? "meter-container-happy":"meter-container-unhappy"%>">
    <div class="<%= v > 40 ? "meter-happy":"meter-unhappy"%>" style="width:<%=v%>%">
      <h2>Happiness</h2>
    </div>
  </div>
  <% v = @pet.pet_hunger.value %>
  <div class="<%= v < 60 ? "meter-container-happy":"meter-container-unhappy"%>">
    <div class="<%= v < 60 ? "meter-happy":"meter-unhappy"%>" style="width:<%=v%>%">
      <h2>Hunger</h2>
    </div>
  </div>
  <% v = @pet.pet_tiredness.value %>
  <div class="<%= v < 80 ? "meter-container-happy":"meter-container-unhappy"%>">
    <div class="<%= v < 80 ? "meter-happy":"meter-unhappy"%>" style="width:<%=v%>%">
      <h2>Tiredness</h2>
    </div>
  </div>
  <% v = @pet.pet_boredom.value %>
  <div class="<%= v < 50 ? "meter-container-happy":"meter-container-unhappy"%>">
    <div class="<%= v < 50 ? "meter-happy":"meter-unhappy"%>" style="width:<%=v%>%">
      <h2>Boredom</h2>
    </div>
  </div>

app/views/pets/edit.html.erb
<%- title "Renaming #{@pet.name}" %>
<article class="dashboard">
  <section class="reservedword profile">
<%= render 'nameform' %>
<%= link_to "Back to Pet's Page", pet_path(@pet), class: "btn-profile"%>
<%= link_to "Back to Pet List", pets_path, class: "btn-profile" %>
  </section>
</article>

app/views/pets/new.html.erb
<%- title "Animal Shelter" %>

<article class="dashboard">
  <%= render "users/user_profile" %>
</section>

	<!-- <h4>Browse Pets</h4> -->

	<!-- <section>
		<p>Sort by type:</p>
		<%#= link_to "Dogs", new_pet_path(:type => "Dog") %>
		<%#= link_to "Cats", new_pet_path(:type => "Cat") %>
		<%#= link_to "Birds", new_pet_path(:type => "Bird") %>
		<%#= link_to "Rabbits", new_pet_path(:type => "Rabbit") %>
    <%#= link_to "All", new_pet_path %>
	</section> -->
	<section class="right-columns">

		<section class="pet profile feature">
			<% unless request.url.include? "type"%>
	  	<h4>Featured Pet</h4>
	  	<%= render "randomform" %>
	  	<% end %>
		</section>

    <div id="pets">
		  <%= render "shelterform" unless User.first.id != 1 %>
    </div>
    </div class="hide">
      <%= will_paginate @pets%>
    </div>
	</section>

	<!-- If the first user isn't Zoobit Shelter, the seed file didn't get loaded correctly-->
	<!-- So far, this is only a problem in the test environment. -->

</article>

app/views/pets/new.js.erb
$('#pets').append('<%= j render(:partial => "pets/shelterform") %>');
<% if @pets.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @pets %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pets/show.html.erb
  <%- title @pet.name %>
  <article class="dashboard">
    <!-- PROFILE -->
    <section class="user profile">
      <h3>Owner</h3>
      <%= link_to image_tag avatar_url(@owner) %>
      <section class="stats">
        <h3><%= @owner.username %></h3>
        <p>Score: <%= @owner.points %></p>
        <p>Pets: <%= @owner.pets.count %>/<%= @owner.pet_slots %></p>
        <p><%= @owner.created_at.strftime("Joined on: %m/%d/%Y") %></p>
        <p><%= @owner.last_sign_in_at.strftime("Last signed in: %m/%d/%Y at %I:%M%p") %></p>

        <% if current_user && current_user.friendships.where(friend_id: @owner.id).empty? && current_user != @owner %>
          <%= link_to "Add #{@owner.username} as a friend", {controller: "friendships", action: "create", user_id: current_user.id, friend_id: @owner.id}, method: :post %>
        <% end %>
      </section>
    </section>

    <!-- PETVIEW -->
    <section class="pet view">
      <h1><%= @pet.name %></h1>
      <% if current_user == @pet.user %>
        <%= link_to 'C', edit_pet_path(@pet) %>
      <% end %>
      <div class="pet-head">
        <%= image_tag(@pet.img_loc) %>
      </div>
      <div class="pet-body">
        <%= image_tag(@pet.body_img) %>
      </div>
    </section>
    <!-- CONTROLS -->
    <section class="info-controls">
      <section class="stats profile">
        <%= render "layouts/flash" %>
        <%= render "pets/status_bars" %>
        <p>Breed: <%= @pet.breed %></p>
        <p>Gender: <%= @pet.gender %></p>
      </section>
      <sections class="controls ">
        <%= link_to "Feed #{@pet.name}", pet_feed_path(@pet), class: "btn-profile"%>
        <%= link_to "Play with #{@pet.name}", pet_play_path(@pet), class: "btn-profile" %>
        <% if current_user == @pet.user %>
          <%= link_to 'Abandon', pet_path(@pet), method: :delete, data: { confirm: "Leave #{ @pet.name } all alone? You will be fined half of your total points for being an irresponsible owner." }, class: "btn-profile-neg" %>
          <% end %>
      </section>
    </section>
  </article>


<!--   <div class="sandbox">
  <div class="<%#= @pet.type %> full-pet">
    <div class="pet-head">
      <%#= image_tag(@pet.img_loc) %>
    </div>
    <div class="pet-body">
      <%#= image_tag(@pet.body_img) %>
    </div>
  </div>
  </div>  -->