config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'home#index'

  resources :pets do
    get :feed
    get :play
    patch :adopt
  end

  resources :users do
    resources :pets
    resources :friends, controller: 'friendships'
  end

  get "/about" => "home#about"
  get "/faq" => "home#faq"
  get "/contact" => "home#contact"
  get "/leaderboard" => "home#leaderboard"
  get "/shelter" => "pets#new"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pets
  has_many :friendships
  delegate :dogs, :cats, :birds, :rabbits, to: :pets
  validates :username, presence: true, :uniqueness => {:case_sensitive => false}
  # Virtual field representing whether user is logged in.
  attr_accessor :login

  #Below method taken from:
  #https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  #Below methods for omniauth are from
  #https://gist.github.com/ivanoats/7076128
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :id)).first_or_create do |user|
      user.provider = auth.provider
      user.id = auth.uid
      user.username = auth.info.nickname.nil? ? auth.info.name : auth.info.nickname
      user.email = auth.info.email.nil? ? "#{user.username}-TEMPORARY@zoobit.net" : auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def earn_points
    self.points += 10
    self.save
    self.pet_slots = 5 if self.points >= 2000 && self.pet_slots < 5
    self.pet_slots = 4 if self.points >= 750 && self.pet_slots < 4
    self.pet_slots = 3 if self.points >= 300 && self.pet_slots < 3
    self.pet_slots = 2 if self.points >= 100 && self.pet_slots < 2
    self.save
  end

  def self.search(query)
    where("username like ?", "%#{query}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:search] && !params[:search].empty?
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.reject { |user| ApplicationHelper.obscene_substring?(user.username) }
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_friends.html.erb
<% if @user.friendships.empty? %>
  <%= @user.username %> doesn't have any friends listed.
  <%= (link_to "Add friends", user_friends_path(@user)) if current_user == @user %>
<% else %>
  <%= link_to "See all #{@user.username}'s friends", user_friends_path(@user), class: "btn-profile" %>
<% end %>

app/views/users/_pet_profile.html.erb
<% if @user.pets.empty? %>
    <h3>No pets yet!</h3>
  <% else %>
    <% @user.pets.each do |pet| %>
      <% pet.update_happiness(Time.now) %>
      <% h = pet.happiness.nil? ? 0 : pet.happiness %>
      <section class="pet profile shelter index">
        <section class="image">
          <%= link_to image_tag(pet.img_loc), user_pet_path(@user, pet) %>
        </section>
        <section class="stats"><h4><%= link_to pet.name, user_pet_path(@user, pet) %></h4>
          <p class="pet-type"><%= pet.type %></p>
          <p class="breed"><%= pet.breed %></p>
          <p class="<%= pet.pet_hunger.value > 50 ? "hungry":""%>"></p>
          <p class="<%= pet.pet_boredom.value > 50 ? "bored":""%>"></p>
          <div class="<%= h > 40 ? "meter-container-happy":"meter-container-unhappy"%>">
            <div class="<%= h > 40 ? "meter-happy":"meter-unhappy"%>" style="width:<%=h%>%">
              <p><%= h %></p>
            </div>
          </div>
        </section>
        <%= link_to "View Pet", user_pet_path(@user, pet), class: "btn-profile" %>
      </section>
    <% end %>
  <% end %>

app/views/users/_user_profile.html.erb
<section class="user profile">
  <%= link_to image_tag avatar_url(@user) %>
  <section class="stats">
    <h3><%= @user.username %></h3>
    <p class="score">Score: <%= @user.points %></p>
    <p class="slots">Pets: <%= @user.pets.count %>/<%= @user.pet_slots %></p>
    <p class="join-date"><%= @user.created_at.strftime("Joined on: %m/%d/%Y") %></p>
    <p class="last-login"><%= @user.last_sign_in_at.strftime("Last signed in: %m/%d/%Y at %I:%M%p") %></p>

    <% if current_user && current_user.friendships.where(friend_id: @user.id).empty? && current_user != @user %>
      <%= link_to "Add #{@user.username} as a friend", {controller: "friendships", action: "create", user_id: current_user.id, friend_id: @user.id}, method: :post %>
    <% end %>
    <%= render "users/friends" %>
  </section>
</section>

app/views/users/index.html.erb
<article class="dashboard">
  <% @users.each do |user| %>
    <!--@KL this section class is hacky as hell, figure out grid sytem better.  If remove shelter and index, it has multiple profiles spanning three columns, is it getting height for some reason? -->
    <section class="user profile shelter index">
      <%= link_to image_tag(avatar_url(user)), user %>
      <section class="stats">
        <h3><%= user.username %></h3>
        <p>Score: <%= user.points %></p>
        <p>Pets: <%= user.pets.count %>/<%= user.pet_slots %></p>
        <p><%= user.created_at.strftime("Joined on: %m/%d/%Y") %></p>
        <p><%= user.last_sign_in_at.strftime("Last signed in: %m/%d/%Y at %I:%M%p") %></p>
      </section>
      <% if current_user && current_user.friendships.where(friend_id: user.id).empty? && current_user != user %>

        <%= link_to "Add Friend", {controller: "friendships", action: "create", user_id: current_user.id, friend_id: user.id}, method: :post, :class => "btn-profile" %>

      <% end %>
    </section>
  <% end %>
</article>

app/views/users/show.html.erb
<%- title "#{@user.username}" %>
<article class="dashboard">
  <%= render "users/user_profile" %>

  <section class="right-columns">

  <%= render "users/pet_profile" %>
</article>