config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'home#index'

  resources :pets do
    get :feed
    get :play
    patch :adopt
  end

  resources :users do
    resources :pets
    resources :friends, controller: 'friendships'
  end

  get "/about" => "home#about"
  get "/faq" => "home#faq"
  get "/contact" => "home#contact"
  get "/leaderboard" => "home#leaderboard"
  get "/shelter" => "pets#new"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    current_uri = request.env['PATH_INFO']
    url_parts = current_uri.split("/")-[""]
    uid = url_parts[1].to_i
    @user = User.find(uid)
    @friends = @user.friendships.all
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(friendship_params) unless current_user.friendships.any? { |f| f.friend_id == :friend_id }
    respond_to do |format|
      if @friendship.save
        friend = User.find(friendship_params["friend_id"]).username
        format.html { redirect_to user_friends_path, notice: "#{friend} was added as a friend." }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to user_friends_path, notice: "Unfriended #{User.find(@friendship.friend_id).username}." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.permit(:user_id, :friend_id, :status)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friend.html.erb
<section class="user profile shelter index"><%= link_to image_tag(avatar_url(@friend)), @friend %>
  <section class="stats">
    <%= link_to @friend.username, @friend %>
    <p>Score: <%= @friend.points%></p>
    <p>Pets: <%= @friend.pets.length %></p>
    <p><%= @friend.created_at.strftime("Joined on: %m/%d/%Y") %></p>
    <p><%= @friend.last_sign_in_at.strftime("Last signed in: %m/%d/%Y at %I:%M%p") %></p>
    <%= link_to 'Unfriend', user_friend_path(@user.id, Friendship.where(friend_id: @friend.id)[0].id), method: :delete, class: "btn-profile" %>
  </section>
</section>

app/views/friendships/_new_friend.html.erb
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
<section class="user profile shelter index">
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search", :name => nil, class: "btn-profile" %>
<% end %>
</section>

app/views/friendships/index.html.erb
<article class="dashboard">

  <%= render "users/user_profile" %>
  <%= render 'new_friend' %>
  <!-- <h2 class="sub-heading"><%= @user.username %>'s Friends:</h2> -->

  <% if current_user.nil? && @user.friendships.empty? %>
    <%= @user.username %> doesn't have any friends listed!
  <% elsif current_user && current_user == @user && @user.friendships.empty? %>
    You don't have any friends in your friend list.
  <% end %>
  <% @user.friendships.each do |friendship| %>
    <% @friend = User.find(friendship.friend_id) %>
    <%= render 'friend' %>
  <% end %>

</article>