config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root 'home#index'

  resources :pets do
    get :feed
    get :play
    patch :adopt
  end

  resources :users do
    resources :pets
    resources :friends, controller: 'friendships'
  end

  get "/about" => "home#about"
  get "/faq" => "home#faq"
  get "/contact" => "home#contact"
  get "/leaderboard" => "home#leaderboard"
  get "/shelter" => "pets#new"
end

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <p data-alert class="alert-box alert radius">
    <%= alert %>
  </p>
<% end %>
  <% if flash[:notice] %>
  <p data-alert class="alert-box success radius">
    <%= notice %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <a href="/about">About</a>
  <a href="/faq">FAQ</a>
  <a href="/contact">Contact</a>
  <a href="#">Donate</a>
</footer>

app/views/layouts/_navigation.html.erb
<header class="header-main" id="top" role="banner">
  <%= image_tag("barger.svg", class: "nav-btn", id:"nav-open-btn", href: "#nav", width: "30px") %>
  <%= link_to image_tag("zoobit-logo.svg", class: "header-logo"), root_path %>
  <h1 class="header-main-heading"><%= link_to "Zoobit", root_path %></h1>
</header>
<nav class="main-nav" id="nav" role="navigation">
  <ul>
    <% if current_user.nil? %>
      <li><%= link_to (raw t(:sign_up_link_html)), new_user_registration_path %><li>
      <li><%= link_to (raw t(:sign_in_link_html)), new_user_session_path  %></li>
    <% else %>
      <li><%= link_to "Your Pets", user_path(current_user) %></li>
      <li><%= link_to "Animal Shelter", new_pet_path %></li>
      <li><%= link_to "Leaderboard", "/leaderboard" %></li>
      <li><%= link_to (raw t(:sign_out_link_html)), destroy_user_session_path, method: :delete %></li>
      <li><p>Signed in as <%= current_user.username %></p></li>
    <% end %>
  </ul>
  <a class="close-btn" id="nav-close-btn" href="#top">Return to Content</a>
</nav>
<!-- <h2><%#= content_for?(:title) ? yield(:title) : "Zoobit" %></h2> -->
<!-- Title Bar -->

app/views/layouts/_omniauthpopup.html.erb
 <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class: "btn-profile" %>
 <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn-profile" %>

app/views/layouts/_sidenav.html.erb
<nav id="side-nav">
  <% if current_user.nil? %>
  <h4>Your pets go here!</h4>
  <% elsif current_user.pets.empty? %>
    <h4>You don't have any pets!</h4>
  <% else %>
    <h4>Your Current Pets:</h4>
<% end %>
<ul>
  <% if current_user.nil? %>
    <li><%= link_to (raw t(:sign_up_link_html)), new_user_registration_path %></li>
    <li><%= link_to (raw t(:sign_in_link_html)), new_user_session_path  %></li>
  <% elsif current_user.pets.empty? %>
    <li>Adopt a <%= link_to 'New Pet', new_pet_path, id: "newpet" %>?</li>
  <% else %>
    <li><article class="profile"><%- title "#{current_user.username}" %>
    <%= link_to image_tag avatar_url(current_user) %>
    <!-- <h2><%#= content_for?(:title) ? yield(:title) : "Zoobit" %></h2> -->
    <section class="stats">
      <h3><%= current_user.username %></h3>
      <p>Score: <%= current_user.points %></p>
      <p>Pets: <%= current_user.pets.count %>/<%= current_user.pet_slots %></p>
      <p><%= current_user.created_at.strftime("Joined on: %m/%d/%Y") %></p>
      <p><%= current_user.last_sign_in_at.strftime("Last signed in: %m/%d/%Y at %I:%M%p") %></p>

      <% if current_user && current_user.friendships.where(friend_id: current_user.id).empty? && current_user != current_user %>
        <%= link_to "Add #{current_user.username} as a friend", {controller: "friendships", action: "create", user_id: current_user.id, friend_id: current_user.id}, method: :post %>
      <% end %>
    </section>
  </article></li>
    <% current_user.pets.each do |pet| %>
      <% pet.update_happiness(Time.now) %>
      <li>
        <section class="profile">
          <section class="image">
        <%= link_to image_tag(pet.img_loc), user_pet_path(current_user, pet) %>
          </section>
          <section class="stats">
        <h4><%= link_to pet.name, user_pet_path(current_user, pet) %></h4>
        <% h = pet.happiness.nil? ? 0 : pet.happiness %>
        <div class="<%= h > 40 ? "meter-container-happy":"meter-container-unhappy"%>">
            <div class="<%= h > 40 ? "meter-happy":"meter-unhappy"%>" style="width:<%=h%>%">
              <p><%= h %></p>
            </div>
          </div>
        </section>
        <%= link_to "View Pet", user_pet_path(current_user, pet), class: "btn-profile" %>
      </section>
      </li>
      <li class="divider"></li>

    <% end %>
    <li><%= link_to (raw t(:sign_out_link_html)), destroy_user_session_path, method: :delete %></li>
    <li><%= link_to "Leaderboard", "/leaderboard" %></li>
  <% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700|Arimo:400,700' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title)+ " | ZooBit" : "ZooBit" %></title>
    <%= stylesheet_link_tag  "application" %>
    <%= javascript_include_tag  "main" %>
    <%= javascript_include_tag  "modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="outer-wrap">
      <div id="inner-wrap">
        <%= render "layouts/navigation" %>
        <%= render "layouts/sidenav" %>
        <main id="main" class="main">
          <%= yield %>
        </main>
        <%= javascript_include_tag "application" %>
        <%= javascript_include_tag 'jquery.inview.min' %>
      </div>
    <!--/#inner-wrap-->
    </div>
    <!--/#outer-wrap-->
    <%#= render "layouts/footer" %>
  </body>
</html>